id: END
version: 0.1.0
author: Aureus

generator: NOISE_3D

addons:
  biome-provider-pipeline: "1.+"
  biome-provider-single: "1.+"
  biome-provider-extrusion: "1.+"
  chunk-generator-noise-3d: "1.+"
  config-biome: "1.+"
  config-flora: "1.+"
  config-noise-function: "1.+"
  config-ore: "1.+"
  config-palette: "1.+"
  config-distributors: "1.+"
  config-locators: "1.+"
  config-feature: "1.+"
  structure-terrascript-loader: "1.+"
  structure-sponge-loader: "1.+"
  language-yaml: "1.+"
  generation-stage-feature: "1.+"
  structure-function-check-noise-3d: "1.+"
  palette-block-shortcut: "1.+"
  structure-block-shortcut: "1.+"
  terrascript-function-sampler: "1.+"

# Default biome distribution
biomes: $biome-providers/presets/default.yml:biomes

# Single biome - to change the single biome to use, check the configuration file.
#biomes: $biome-providers/presets/single.yml:biomes


stages:
  # Used to generate lava at the bottom of the world.
  # NOTE - This key must only be defined in biomes/abstract/base.yml
  - id: global-preprocessors
    type: FEATURE
  
  # Misc features that are treated as small modifications to the initial chunk generation.
  - id: preprocessors
    type: FEATURE
  
  # Used for things like boulders and features that act like a part of the terrain.
  - id: landforms
    type: FEATURE
  
  # Adds slab versions of some blocks to make terrain look smoother.
  - id: slabs
    type: FEATURE
  
  # Self-explanatory - used to generate ores.
  # NOTE - Individual biomes should extend from configs in biomes/abstract/features/ores
  #        rather than overwriting this key themselves.
  - id: ores
    type: FEATURE
  
  # Adds things like dirt, andesite and gravel patches.
  # NOTE - Individual biomes should extend from configs in biomes/abstract/features/deposits
  #        rather than overwriting this key themselves.
  - id: deposits
    type: FEATURE
  
  # Used for biome specific river variant features.
  # NOTE - Individual biomes should extend from configs in biomes/abstract/features/river
  #        rather than overwriting this key themselves.
  - id: river-decoration
    type: FEATURE
  
  # Used for larger things that generate on the surface like trees, some other features are
  # also treated as trees like ice spikes.
  - id: trees
    type: FEATURE
    
  # Used for small features placed underwater like sea-grass.
  - id: underwater-flora
    type: FEATURE
    
  # Used for small features placed on the surface like tall grass and vines.
  - id: flora
    type: FEATURE
  
  # Used to generate features that must come after all other features, such as snow on trees.
  - id: postprocessors
    type: FEATURE

samplers:
  "<<":
    - math/samplers/simplex.yml:samplers

functions:
  lerp:
    # Linear interpolation between two values
    arguments:
      - t
      - at # Value of t where output = a
      - a
      - bt # Value of t where output = b
      - b
      # Values of t between at and bt will be interpolated
    expression: |
      if(at<bt,
        if(t<=at,a,if(t>=bt,b,a*(t-bt)/(at-bt)+b*(t-at)/(bt-at))),
        if(t>=at,a,if(t<=bt,b,a*(t-bt)/(at-bt)+b*(t-at)/(bt-at)))
      )